package gui.splashScreen;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Principal.java
 *
 * Created on 20 avr. 2013, 20:14:56
 */


import gui.AuthenticationGUI;

import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author DELL
 */
public class Principal extends javax.swing.JFrame {

    /** Creates new form Principal */
    public Principal() {
        initComponents();
        new Thread(){
            public void run(){
                for (int i=0;i<101;i++){
                    try {
                        sleep(15);
                        progresso.setValue(i);

                    } catch (InterruptedException ex) {
                        Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
                AuthenticationGUI a = new AuthenticationGUI();
                a.setVisible(true);
                a.setLocationRelativeTo(null);
                
            }


        }.start();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        progresso = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.BorderLayout());
        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/splashscreen2.jpg")));
     //   lblNewLabel.setIcon(new ImageIcon(sss.class.getResource("/images/splashscreen1.jpg")));
        jPanel2.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        progresso.setStringPainted(true);
        jPanel2.add(progresso, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                final Principal p = new Principal();
                p.setVisible(true);
                p.setLocationRelativeTo(null);

        new Thread(){
                    @Override
            public void run(){
                        try {
                            sleep(2000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(Principal.class.getName()).log(Level.SEVERE, null, ex);
                        }
                p.setVisible(false);
            }
         }.start();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JProgressBar progresso;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the progresso
     */
    public javax.swing.JProgressBar getProgresso() {
        return progresso;
    }

}
